delete from payment.categories;
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (1, 'Consultation', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (2, 'X-RAY', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (3, 'Scaling & polishing', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (4, 'Orthodontic Rx', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (5, 'Filling', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (6, 'Bridge', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (7, 'Denture', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (8, 'Extraction', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (9, 'Surgical', 'f');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (10, 'Root canal treatment', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (11, 'Bleaching', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (12, 'Category 12', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (13, 'Category 13', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (14, 'Category 14', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (15, 'Category 15', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (16, 'Category 16', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (17, 'Category 17', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (18, 'Category 18', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES (19, 'Category 19', 't');
