delete from payment.categories;
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('1', 'Doctor visit', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('2', 'X-RAY', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('3', 'Cleaning', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('4', 'Root planing', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('5', 'Treatments', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('6', 'Composite filling front', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('7', 'Composite filling back', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('8', 'Amalagma filling', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('9', 'Repair', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('10', 'Crown/Bridge', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('11', 'Root canal treatment', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('12', 'Extraction', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('13', 'Denture', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('14', 'Bleaching', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('15', 'Brace', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('16', 'Emergency tretment', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('17', 'Removal appliance', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('18', 'Category 18', 't');
INSERT INTO "payment"."categories" ("id", "name", "active") VALUES ('19', 'Others', 't');
