CREATE TABLE public.accounts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    full_name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO public.accounts (username, full_name, created_at)
VALUES
    ('mmorgan', 'Melissa Morgan', CURRENT_TIMESTAMP),
    ('tcoleman', 'Tristan Coleman', CURRENT_TIMESTAMP);
select * from public.accounts;

GRANT SELECT ON public.accounts TO jkatz;

CREATE POLICY accounts_policy
ON public.accounts
USING (username = CURRENT_USER);



-- Prevent SQL deletes
create rule protect_posts as on delete to posts do instead nothing;
--
select type, count(*), count(*)::numeric / sum(count(*)) over ()
from pets
group by type;
--